name: KnightCore
version: ${project.version}
main: ml.knightcraft.core.Main
api-version: 1.16
load: STARTUP
authors: [Hoptilic]
description: Core for KnightCraft
website: knightcraft.ml
commands:
  punish:
    description: "Test"
    aliases: p
    usage: </command>
  credits:
    description: "Shows the credits for everyone involved in the server"
    usage: </command>